Fix indentation of ldap_ca.crt data
netbox-community/netbox-chart pull request #307
Opened 2024-08-14 11:48 UTC by devasmith

- It looks like a pipe symbol was added at the top of the ldap_ca.crt data file

I think that the `nindent` can cause this as it prepends a new line.

Cert data was defined like this:

```
        caCertData: |
          -----BEGIN CERTIFICATE-----
          ...
          -----END CERTIFICATE-----
```

Output in the ldap_ca.crt file:

```
  ldap_ca.crt: |-
  |
    -----BEGIN CERTIFICATE-----
```

2024-08-14 11:50 UTC, devasmith commented
@LeoColomb I'm not sure if you stumbled upon this before but it is the only thing I can think of that may cause the unwanted pipe character.

2024-08-14 12:28 UTC, LeoColomb requested changes
Thanks for your PR.
Changing the indentation won't fix the YAML validity.
As the template is using `toYaml` function, the output is a valid YAML multiline value. There is no need to describe a multiline again.

2024-08-14 12:28 UTC, LeoColomb requested changes
Thanks for your PR.
Changing the indentation won't fix the YAML validity.
As the template is using `toYaml` function, the output is a valid YAML multiline value. There is no need to describe a multiline again.

2024-08-14 12:28 UTC, LeoColomb commented on charts/netbox/templates/configmap.yaml
>    ldap_ca.crt: |-
```suggestion
  ldap_ca.crt: {{- toYaml $.Values.remoteAuth.ldap.caCertData | indent 4 }}
```

2024-08-14 12:33 UTC, LeoColomb commented on charts/netbox/templates/configmap.yaml
> +    {{- toYaml $.Values.remoteAuth.ldap.caCertData | indent 2 }}
```suggestion
```

2024-08-14 13:09 UTC, devasmith commented
> Thanks for your PR. Changing the indentation won't fix the YAML validity. As the template is using `toYaml` function, the output is a valid YAML multiline value. There is no need to describe a multiline again.

That makes sense, thanks for the explanation. 👍

2024-08-15 17:27 UTC, RangerRick approved these changes

2024-08-15 17:27 UTC, merged