External secret for email password
netbox-community/netbox-chart pull request #426
Opened 2024-12-03 07:18 UTC by KittyKatt

Noticed that this was one of the only credentials I couldn't slap into an external secret and source from the chart. This should allow that functionality. I did test locally and it looked like it put the value in all of the right places. Didn't find a whole lot about guidelines on contributing, so let me know if there's anything additional I need to do. Thanks!

2024-12-03 13:01 UTC, LeoColomb requested changes
Thanks for submitting this pull request, @KittyKatt.
All fine on the contribution flow 😊

Please see my inline comments to avoid too many local helpers.

All in all, I'm not a huge fan of the current secret structure.
I'm considering splitting every secret data into its own instance, per domain (i.e. netbox-admin, email, ldap, etc.).
Would that make more sense? (/cc @RangerRick)

2024-12-03 13:01 UTC, LeoColomb commented on charts/netbox/templates/cronjob.yaml
> +                  name: {{ include "netbox.email.secret" . | quote }}
```suggestion
                  name: {{ include "common.secrets.name" (dict "existingSecret" (default .Values.email.existingSecretName .Values.existingSecret) "defaultNameSuffix" "config" "context" $) }}
```

2024-12-03 13:01 UTC, LeoColomb commented on charts/netbox/templates/_helpers.tpl
> +
```suggestion
```

2024-12-03 13:01 UTC, LeoColomb commented on charts/netbox/templates/deployment.yaml
> +              name: {{ include "netbox.email.secret" . | quote }}
```suggestion
              name: {{ include "common.secrets.name" (dict "existingSecret" (default .Values.email.existingSecretName .Values.existingSecret) "defaultNameSuffix" "config" "context" $) }}
```

2024-12-03 13:01 UTC, LeoColomb commented on charts/netbox/templates/worker/deployment.yaml
> +              name: {{ include "netbox.email.secret" . | quote }}
```suggestion
              name: {{ include "common.secrets.name" (dict "existingSecret" (default .Values.email.existingSecretName .Values.existingSecret) "defaultNameSuffix" "config" "context" $) }}
```

2024-12-03 23:52 UTC, KittyKatt commented
Splitting up the secrets into function is certainly not a bad idea. It seems you've already done a fair deal of that, if you're talking about what I think you are. Also, thanks for the suggestions. Committing now.

2024-12-04 10:54 UTC, LeoColomb approved these changes

2024-12-06 06:10 UTC, KittyKatt commented
@LeoColomb Is there something specific I need to do to pass the failing check? Is it just increasing Chart `version` in Chart.yaml to `5.0.0-beta.155`?

2024-12-06 10:18 UTC, LeoColomb commented
@KittyKatt Yes, a bump if the version would make it pass. 😊
Thanks!

2024-12-06 17:20 UTC, merged

2024-12-07 03:11 UTC, KittyKatt commented
> @KittyKatt Yes, a bump of the version would make it pass. 😊
> Thanks!

Thanks! Sorry I didn't see it sooner. Happy to see it get merged!