docs: add migration guide from bootc/netbox-chart to netbox-community/netbox-chart
netbox-community/netbox-chart pull request #446
Opened 2024-12-13 11:55 UTC by davidusken

Adding a migration guide on how to migrate from bootc/netbox-chart to netbox-community/netbox-chart

I can also add all the ArgoCD specific parts if this is of any interest

2024-12-16 17:32 UTC, RangerRick commented
Thanks for this!

@LeoColomb and I were talking about this and are thinking we should break this up into 2 parts.
1. a general guideline on how to do an upgrade (dump the database, transition through minor versions)
2. taking these specific notes of yours and making them part of the "breaking changes" release notes for 5.0.0

For the former, I'm happy to modify this PR to turn it into a summary, if you'd like.
For the latter, we're tracking 5.0.0 stuff over in [this PR](https://github.com/netbox-community/netbox-chart/pull/286).

2024-12-18 16:14 UTC, RangerRick commented
I've gone ahead and converted your `migrate.md` to a more generic wording, since the specifics got pulled into the 5.0 release PR. I'll merge this now.

Thanks again for doing the work of creating proper steps for migrating! It's really appreciated.

2024-12-18 16:17 UTC, LeoColomb requested changes
One typo, otherwise looks perfect to me 👍

2024-12-18 16:17 UTC, LeoColomb commented on docs/migrate.md
> +It is recommmended that you upgrade to the latest supported PostgreSQL version.
```suggestion
It is recommended that you upgrade to the latest supported PostgreSQL version.
```

2024-12-18 16:41 UTC, merged